name: Test deployment

on:
  pull_request:
    branches:
     # change this branch name incase v5 branch is deleted/moved.
      - v5
    paths: 
      - "website/**"
      - "**.ts"
      - "README.md"
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    # setting the working directory as that's where the docs/website exists.
    defaults:
      run:
        working-directory: ./website
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Write docusaurus heading ids
        run: npm run write-heading-ids
      - name: Test build website
        run: npm run build